const assert = require("assert");
let {problem} = require("../src/problem2");

let limit = 4000000;
let answer = 4613732;

describe( "Problem 2 :Even Fibonacci numbers\n Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:\n 1,2,3,5,8,13,21,34,55,89,...\n\n By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.\n", ()=>{
    it(`Should return the answer : ${answer}`, ()=>{
        assert( problem(limit) === answer, `Answer should be ${answer}` );
    });
});
